name: Hc3
description: Blog feito para compartilhar meus estudos.
meta_description: "Blog sobre desenvolvimento,Javascript,Webschool,Java,Php"

markdown: kramdown
highlighter: pygments
logo: true
paginate: 15
baseurl: /
domain_name: 'https://hc3.github.io/'
google_analytics: 'UA-XXXXXXXX-X'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'https://hc3.github.io/'
author:         'Hc3'
